name: pdf_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  pdf: ^3.11.3
  flutter_image_compress: ^2.4.0
  syncfusion_flutter_pdf: ^31.1.23
  printing: ^5.14.2
  image: ^4.5.4
  share_plus: ^12.0.0
  permission_handler: ^12.0.1
  syncfusion_flutter_pdfviewer: ^31.1.23
  flutter_quill: ^11.4.2
  reorderable_grid_view: ^2.2.8
  pdf_render: ^1.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
